name: 'Ascend resource content'
description: 'Ascend resource demo content - installs terms for category, stage, pricing vocabularies'
type: 'Default content'
recipes:
  - resource
install:
  - ascend_resource
