name: 'Ascend resource setup'
description: 'Ascend resource setup recipe - installs modules and sets up config'
type: 'Content type'
recipes:
  # Can't depend on other recipes outside of this dir or core!
install:
  - media
  - media_entity_download
  - ascend_resource
config:
  strict: true
  import:
    ascend_resource: '*'
  actions:
    user.role.anonymous:
      grantPermissions:
        - 'view resource'
        - 'download media'
    user.role.authenticated:
      grantPermissions:
        - 'view resource'
        - 'download media'
    user.role.content_editor:
      grantPermissions:
        - 'edit terms in category'
        - 'use taxonomy_term.edit_info form mode'
        # Access the Files overview page ?
    user.role.user_manager:
      grantPermissions:
        - 'assign resource_manager role'
