name: 'Ascend resource setup'
description: 'Ascend resource setup recipe - installs modules and sets up config'
type: 'Content type'
recipes:
  # Can't depend on other recipes outside of this dir or core!
install:
  - media
  - media_entity_download
  - search_api
  - search_api_db
  - search_api_autocomplete
  - ascend_resource
config:
  strict: true
  import:
    ascend_resource: '*'
  actions:
    form_mode_manager.links:
      simpleConfigUpdate:
        local_tasks.resource:
          position: primary
    content_lock.settings:
      simpleConfigUpdate:
        types.resource:
          '*': '*'
        form_op_lock.resource:
          mode: 0
          values: {  }
    user.role.anonymous:
      grantPermissions:
        - 'view resource'
        - 'download media'
    user.role.authenticated:
      grantPermissions:
        - 'view resource'
        - 'download media'
    user.role.content_editor:
      grantPermissions:
        - 'edit terms in category'
        - 'use taxonomy_term.edit_info form mode'
        # Access the Files overview page?
    user.role.user_manager:
      grantPermissions:
        - 'assign resource_manager role'
    user.role.site_manager:
      grantPermissions:
        - 'create terms in pricing'
        - 'create terms in stage'
        - 'edit terms in pricing'
        - 'edit terms in stage'
        - 'use taxonomy_term.default form mode'
        - 'masquerade as resource manager'
    core.entity_form_display.taxonomy_term.category.default:
      setComponent:
        name: ascend_info
        options:
          type: text_textarea
          weight: 5
          region: content
          settings:
            rows: 5
            placeholder: ''
          third_party_settings: { }
